### ISSUE TITLE
does this work on Slackware 15.0?

### ISSUE THREAD

**Issue by anoraktrend** [mumahendras3/sl6ckware#12]
Just asking for future reference.

**Comment by mumahendras3** [comment]
Hi,

Yes, it should work with Slackware 15.0.

I'll create a separate branch for 15.0 later when I have the time, especially when I'll be updating the random seed generation part to use seedrng utility (as per -current ChangeLog) instead of the old way like in 15.0.

**Comment by mumahendras3** [comment]
As per the README update, I have created the “15.0” branch for use on Slackware 15.0 systems and the “current” branch for use on Slackware-current.

Cheers!
