### ISSUE TITLE
crond syslog dependency and environment

### ISSUE THREAD

**Issue by belka-ew** [mumahendras3/sl6ckware#4]
I have 2 suggestions regarding rc.crond.

- Get rid of the syslog dependency. Crond has `-L` option to write to a file, so it can write its logs to stdout with `-f -l notice -L /dev/stdout`
- Running crond in a clean environment (`exec -c $CMD $CMD_OPTS`) is not that great. Cronjobs are executed in the same environment and this means that the cronjobs don't even have the PATH set. I would replace `exec -c $CMD $CMD_OPTS` in `rc.crond/crond/run` with just `$CMD $CMD_OPTS`, ot set a sane PATH at least before executing into crond.

If you agree on one or both of these changes, I can create a pull request.

**Comment by mumahendras3** [comment]
Thanks for looking into this.

>     * Get rid of the syslog dependency.

Yeah you're right, that probably shouldn't be there.

>     Crond has `-L` option to write to a file, so it can write its logs to stdout with `-f -l notice -L /dev/stdout`

Well, crond's man page states:

```
-f     run crond in the foreground.  All log messages are sent to stderr instead of syslog or a -L file.
```

so using `-f` should be sufficient, no?

>     * Running crond in a clean environment (`exec -c $CMD $CMD_OPTS`) is not that great. Cronjobs are executed in the same environment and this means that the cronjobs don't even have the PATH set. I would replace `exec -c $CMD $CMD_OPTS` in `rc.crond/crond/run` with just `$CMD $CMD_OPTS`, ot set a sane PATH at least before executing into crond.

Good point. I prefer more on the line of setting a sane PATH. We can use something similar to what I have done on rc.openldap, which goes along something like below:

```
fdmove -c 2 1
if { mkdir -p /var/run/cron }
emptyenv -p
s6-envdir env
multisubstitute {
  importas -u CMD CMD
  importas -usCd" " CMD_OPTS CMD_OPTS
}
emptyenv -c $CMD $CMD_OPTS
```

This way, the user can then put every environment variables that crond needs inside the `env` directory while still providing a clean and predictable environment for crond. We can then put a sane PATH there too (probably something like `/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin` or other else if you have a better one).

How does that sound to you?

> If you agree on one or both of these changes, I can create a pull request.

If you want to create a pull request for them, it'll be much appreciated.

**Comment by belka-ew** [comment]
> so using `-f` should be sufficient, no?

I was confused, because I've seen `/var/log/crond` created over night. But it turns out, logrotate creates an empty `/var/log/crond`. Thanks for pointing that out.
